SET NAMES utf8mb4;

UPDATE articles SET
  title_en = 'Introduction to Nuclear Medicine',
  excerpt_en = 'Nuclear medicine is a medical specialty that uses radioactive tracers to diagnose and treat diseases. Learn what it is, how it works, and why it is safe.',
  content_en = '<p>Nuclear medicine is a specialized branch of medical imaging that uses small amounts of radioactive material — called radiotracers or radiopharmaceuticals — to diagnose and, in some cases, treat diseases. Unlike conventional X-rays that show the structure of organs, nuclear medicine imaging shows how organs <strong>function</strong> in real time.</p><p>Radiotracers are administered to the patient (usually by injection, swallowing, or inhalation). They travel to the target organ and emit gamma rays that are detected by a special camera — the gamma camera — which creates detailed images of the organ from the inside.</p><h3>Why Choose Nuclear Medicine?</h3><ul><li>Detects disease at the earliest biological stage — often before structural changes appear on CT or MRI.</li><li>Completely non-invasive with no surgical procedures required.</li><li>The radiation dose is minimal and comparable to a standard X-ray.</li><li>Provides functional and metabolic information no other modality can match.</li></ul><p>At Caspian Nuclear Medicine Center, we use state-of-the-art SPECT and PET scanners combined with the expertise of board-certified nuclear medicine physicians to deliver the most accurate diagnoses possible.</p>'
WHERE id = 1;

UPDATE articles SET
  title_en = 'How Dangerous Is Radiation Exposure During a Nuclear Scan?',
  excerpt_en = 'Patients often worry about radiation during nuclear medicine scans. Here we explain the actual dose, compare it to everyday sources, and clarify the real risks.',
  content_en = '<p>One of the most common questions patients ask before a nuclear medicine scan is: <em>"Is the radiation dangerous?"</em> The short answer is: the radiation dose used in diagnostic nuclear medicine is <strong>very low</strong> and considered safe for the vast majority of patients.</p><h3>Putting the Dose in Perspective</h3><p>The effective radiation dose for a typical nuclear medicine scan (such as a bone scan or thyroid scan) ranges from 1 to 10 millisieverts (mSv). To put this in context:</p><ul><li>A chest X-ray delivers about 0.1 mSv.</li><li>The average person receives about 2–3 mSv per year from natural background radiation.</li><li>A transatlantic flight exposes you to about 0.1 mSv.</li></ul><p>The radiotracer used in the scan is chosen to decay rapidly. Most tracers are eliminated from the body within hours to a few days, further reducing cumulative exposure.</p><h3>Who Should Take Extra Precautions?</h3><p>Pregnant women and nursing mothers should inform their doctor before any nuclear medicine procedure. While even in these groups the benefit often outweighs the risk, alternative imaging methods may be considered. Children receive weight-adjusted doses to keep exposure as low as reasonably achievable (ALARA principle).</p><p>Our medical team at Caspian Nuclear Medicine Center carefully reviews each patient case and selects the tracer and protocol that delivers the diagnostic information needed with the lowest possible radiation dose.</p>'
WHERE id = 2;

UPDATE articles SET
  title_en = 'What Is a SPECT Scan and How Is It Different from MRI?',
  excerpt_en = 'SPECT and MRI are both advanced imaging tools, but they work very differently. Discover what SPECT shows that MRI cannot — and when each is the right choice.',
  content_en = '<p>Both SPECT (Single Photon Emission Computed Tomography) and MRI (Magnetic Resonance Imaging) are powerful diagnostic tools, but they serve very different purposes and rely on completely different physical principles.</p><h3>How SPECT Works</h3><p>SPECT is a nuclear medicine technique. A small amount of radioactive tracer is injected into the bloodstream. As it accumulates in the target tissue, it emits gamma rays that are captured by rotating cameras around the patient. A 3D map of tracer distribution is then reconstructed — showing <strong>metabolic activity and blood flow</strong> within organs.</p><h3>How MRI Works</h3><p>MRI uses strong magnetic fields and radio waves to align hydrogen atoms in the body and detect the energy they release. It produces extremely detailed images of soft tissue <strong>anatomy and structure</strong> — without any ionizing radiation.</p><h3>Key Differences at a Glance</h3><table><tr><th>Feature</th><th>SPECT</th><th>MRI</th></tr><tr><td>What it shows</td><td>Function / metabolism</td><td>Anatomy / structure</td></tr><tr><td>Radiation</td><td>Low-dose ionizing</td><td>None</td></tr><tr><td>Best for</td><td>Heart, brain, bone perfusion</td><td>Brain, spine, joints, soft tissue</td></tr><tr><td>Scan time</td><td>20–40 minutes</td><td>30–60 minutes</td></tr></table><p>In many clinical scenarios, SPECT and MRI are complementary — the functional data from SPECT combined with the structural detail from MRI gives physicians a complete picture of the patient condition.</p>'
WHERE id = 3;

UPDATE articles SET
  title_en = 'The Importance of Early Detection of Heart Disease',
  excerpt_en = 'Heart disease is the leading cause of death worldwide. Early detection through nuclear cardiology can save lives by identifying problems before a heart attack occurs.',
  content_en = '<p>Cardiovascular disease remains the number one cause of death globally. Yet many heart conditions are <strong>completely treatable</strong> when caught early. Nuclear cardiology — specifically myocardial perfusion imaging (MPI) — is one of the most powerful tools available for early detection.</p><h3>What Is Myocardial Perfusion Imaging?</h3><p>MPI is a nuclear medicine test that shows how well blood flows through the heart muscle at rest and during stress. A radiotracer is injected and a gamma camera captures its uptake in the heart. Areas with reduced blood flow (ischemia) or scarring from a previous heart attack (infarction) appear as cold spots on the image.</p><h3>Why Early Detection Matters</h3><ul><li><strong>Prevents heart attacks:</strong> Detecting blocked arteries before a cardiac event allows intervention through medication, angioplasty, or stenting.</li><li><strong>Guides treatment:</strong> Physicians can tailor medication, lifestyle changes, and procedures based on the precise location and severity of the disease.</li><li><strong>Reduces mortality:</strong> Studies consistently show that patients whose heart disease is detected and managed early live longer, healthier lives.</li><li><strong>Cost-effective:</strong> Prevention and early-stage treatment cost far less than emergency care or cardiac surgery.</li></ul><p>If you have risk factors such as high blood pressure, diabetes, high cholesterol, obesity, or a family history of heart disease, a preventive nuclear cardiology evaluation at Caspian Nuclear Medicine Center could be one of the most important steps you take for your health.</p>'
WHERE id = 4;

UPDATE articles SET
  title_en = '10 Daily Habits for a Healthy Heart',
  excerpt_en = 'Small daily choices add up to a lifetime of heart health. Here are 10 evidence-based habits that cardiologists recommend for protecting your cardiovascular system.',
  content_en = '<p>Your heart beats about 100,000 times a day. The daily habits you choose directly determine how efficiently — and how long — it keeps beating. Here are ten evidence-based habits that cardiologists and preventive medicine specialists consistently recommend:</p><ol><li><strong>Move every day.</strong> At least 30 minutes of moderate aerobic exercise (brisk walking, swimming, cycling) most days of the week strengthens the heart muscle and lowers blood pressure.</li><li><strong>Eat a heart-friendly diet.</strong> Prioritize vegetables, fruits, whole grains, legumes, fish, and healthy fats (olive oil, nuts). Limit processed foods, sodium, and saturated fat.</li><li><strong>Quit smoking — completely.</strong> Smoking is one of the strongest risk factors for heart disease. The risk begins to drop within just 24 hours of quitting.</li><li><strong>Limit alcohol.</strong> Excessive alcohol raises blood pressure and can damage the heart muscle. If you drink, do so in moderation.</li><li><strong>Manage stress.</strong> Chronic stress raises cortisol and adrenaline, which over time damage blood vessels. Meditation, yoga, and social connection all help.</li><li><strong>Sleep 7–9 hours per night.</strong> Poor sleep is linked to hypertension, obesity, and increased cardiovascular risk.</li><li><strong>Know your numbers.</strong> Regularly check blood pressure, blood sugar, cholesterol, and BMI. Early abnormalities can be corrected before they cause damage.</li><li><strong>Stay at a healthy weight.</strong> Every kilogram of excess weight increases the work your heart must do.</li><li><strong>Stay hydrated.</strong> Even mild dehydration thickens the blood and makes the heart work harder.</li><li><strong>Schedule regular check-ups.</strong> Preventive screenings — including nuclear cardiology stress tests when indicated — can detect problems years before symptoms appear.</li></ol><p>Small consistent choices compound over decades. Start today — your future heart will thank you.</p>'
WHERE id = 5;

UPDATE articles SET
  title_en = 'Everything About the Thyroid Gland — What You Need to Know',
  excerpt_en = 'The thyroid is a small gland with enormous influence over your entire body. Learn how it works, what can go wrong, and how nuclear medicine helps diagnose thyroid disorders.',
  content_en = '<p>The thyroid gland is a butterfly-shaped structure in the front of the neck, weighing only 20–30 grams. Despite its small size, it has an outsized impact on virtually every cell in the body. It produces two key hormones — T3 (triiodothyronine) and T4 (thyroxine) — that regulate metabolism, energy, temperature, heart rate, mood, and much more.</p><h3>Common Thyroid Disorders</h3><ul><li><strong>Hypothyroidism:</strong> The thyroid produces too little hormone. Symptoms include fatigue, weight gain, feeling cold, depression, and constipation. It is treated with synthetic thyroid hormone (levothyroxine).</li><li><strong>Hyperthyroidism:</strong> The thyroid is overactive. Symptoms include rapid heartbeat, weight loss, anxiety, heat intolerance, and tremors. Graves disease is the most common cause.</li><li><strong>Thyroid nodules:</strong> Lumps within the thyroid gland, most of which are benign. A minority may be malignant, and nuclear medicine helps distinguish them.</li><li><strong>Thyroid cancer:</strong> Highly treatable when caught early, especially with radioiodine therapy.</li></ul><h3>How Nuclear Medicine Evaluates the Thyroid</h3><p>Nuclear medicine offers two main tools for thyroid assessment:</p><p><strong>Thyroid scintigraphy (thyroid scan):</strong> A small dose of radioiodine (I-123) or technetium is given. The gamma camera creates an image showing which parts of the thyroid are functioning normally, overactive (hot nodules), or underactive (cold nodules, which need further evaluation).</p><p><strong>Radioiodine therapy (I-131):</strong> Used to treat hyperthyroidism and certain thyroid cancers. The thyroid absorbs iodine naturally; radioactive iodine selectively destroys overactive or cancerous thyroid tissue with minimal effect on surrounding structures.</p><p>If you have a family history of thyroid disease or are experiencing unexplained fatigue, weight changes, or neck swelling, contact Caspian Nuclear Medicine Center for a comprehensive thyroid evaluation.</p>'
WHERE id = 6;

UPDATE articles SET
  title_en = 'Did You Know? Why We Inject Radioactive Liquid',
  excerpt_en = 'The idea of injecting radioactive material sounds alarming — but the science behind it is reassuring. Here is a plain-language explanation of how radiotracers work and why they are safe.',
  content_en = '<p>When patients hear the words <em>"radioactive injection"</em> before a nuclear medicine scan, it is natural to feel concerned. Let us explain exactly what is being injected, why, and why you have nothing to fear.</p><h3>What Is a Radiotracer?</h3><p>A radiotracer (also called a radiopharmaceutical) is a molecule made up of two parts:</p><ol><li>A <strong>pharmaceutical component</strong> — a molecule that naturally travels to a specific organ or tissue in the body (for example, a molecule similar to glucose that cancer cells absorb rapidly).</li><li>A <strong>radioactive component</strong> — a short-lived radioactive atom attached to the pharmaceutical, which emits detectable gamma rays.</li></ol><p>Together, they allow the gamma camera to track exactly where the pharmaceutical goes inside the body — revealing how that organ is functioning.</p><h3>How Short-Lived Are They?</h3><p>Most radiotracers used in nuclear medicine have extremely short half-lives. Technetium-99m — the most commonly used radiotracer in the world — has a half-life of just 6 hours. This means that within 24 hours, 94% of the radioactivity has decayed away naturally. The remainder is excreted in urine and feces.</p><h3>Is the Quantity Dangerous?</h3><p>The amounts used are genuinely tiny — we are talking about billionths of a gram. The dose is carefully calculated by a nuclear medicine physician and a medical physicist to deliver the diagnostic information needed while keeping radiation exposure as low as possible. The injected material has no pharmacological effect and causes no allergic reactions in the vast majority of patients.</p><p>The next time a nuclear medicine scan is recommended for you, remember: the small amount of radioactivity is a precisely engineered diagnostic tool — not a hazard.</p>'
WHERE id = 7;

UPDATE articles SET
  title_en = 'Did You Know? How We Detect Cancer Earlier Than MRI',
  excerpt_en = 'PET scanning can identify cancer at a cellular level — often years before a tumor is large enough to appear on MRI or CT. Here is how it works.',
  content_en = '<p>One of nuclear medicine most remarkable capabilities is the detection of cancer at a <strong>metabolic and cellular level</strong> — long before structural imaging like MRI or CT can see anything abnormal. The key technology behind this is PET (Positron Emission Tomography), particularly PET-CT scanning.</p><h3>The Warburg Effect: Cancer Glucose Hunger</h3><p>In the early 20th century, biochemist Otto Warburg observed that cancer cells consume glucose at a rate far higher than normal cells — a phenomenon now called the Warburg effect. PET imaging exploits this biological quirk.</p><p>A radioactive form of glucose — called FDG (fluorodeoxyglucose) — is injected into the patient. Cancer cells, hungry for glucose, absorb FDG rapidly and in large quantities. The PET camera detects the radiation emitted and creates a 3D map of FDG distribution throughout the body. Hotspots of FDG uptake reveal where cancer cells are concentrated — even when the tumor is only a few millimeters in size.</p><h3>What MRI and CT Cannot See</h3><p>MRI and CT are structural imaging tools — they show anatomy. A tumor must grow to a certain size before it distorts normal anatomy enough to be visible. PET, by contrast, detects abnormal metabolism. A cluster of cancer cells with elevated glucose consumption will light up on a PET scan long before it forms a visible mass.</p><h3>Clinical Impact</h3><ul><li>Earlier staging of cancers (lung, lymphoma, colorectal, melanoma, and more)</li><li>Distinguishing active tumor from scar tissue after treatment</li><li>Detecting cancer recurrence months before other imaging shows it</li><li>Guiding biopsy to the most metabolically active — and therefore most representative — part of a tumor</li></ul><p>At Caspian Nuclear Medicine Center, our PET-CT service gives oncologists the information they need to make the most accurate treatment decisions at every stage of cancer care.</p>'
WHERE id = 8;

UPDATE articles SET
  title_en = 'Did You Know? Why You Must Fast Before a Scan',
  excerpt_en = 'Fasting before certain nuclear medicine scans is not arbitrary — it directly affects image quality and diagnostic accuracy. Here is the science behind it.',
  content_en = '<p>If you have been scheduled for a nuclear medicine scan and told to fast for 4–6 hours beforehand, you may have wondered: <em>Why does it matter if I eat?</em> The answer lies in the biochemistry of how radiotracers work — and it is a crucial part of getting an accurate result.</p><h3>The FDG-PET Case: The Clearest Example</h3><p>For FDG-PET scans (used to detect cancer, assess brain metabolism, and evaluate cardiac viability), fasting is essential. Here is why:</p><p>FDG (fluorodeoxyglucose) competes with real glucose for uptake by cells. After you eat, your blood glucose level rises sharply. High blood glucose means there is a lot of competition for the FDG — normal cells absorb more of the real glucose and leave less room for FDG. This lowers the contrast between normal and abnormal tissue, making tumors or metabolically active lesions harder to see.</p><p>Additionally, elevated insulin after a meal redirects FDG toward muscle tissue (especially heart muscle), creating background noise that can obscure lesions.</p><h3>How Long Should You Fast?</h3><p>For FDG-PET scans: typically 4–6 hours of fasting is required. Water and plain medications are generally allowed. Your blood glucose level will be measured before the injection — if it is above a certain threshold, the scan may be rescheduled to ensure accuracy.</p><h3>Other Scans That Require Fasting</h3><ul><li><strong>Hepatobiliary (HIDA) scan:</strong> Requires fasting to ensure the gallbladder has accumulated bile and will respond to the CCK stimulant used in the study.</li><li><strong>Gastric emptying study:</strong> Requires a standardized meal and prior fasting to get accurate baseline measurements.</li></ul><p>Always follow the specific fasting instructions provided by our team. If you accidentally eat before your appointment, call us immediately — in many cases we can reschedule rather than compromise the diagnostic value of your scan.</p>'
WHERE id = 9;

UPDATE articles SET
  title_en = 'How to Build Stronger Bones',
  excerpt_en = 'Bone health is not just about calcium — it is a lifelong process involving nutrition, exercise, hormones, and preventive screening. Learn what works and what does not.',
  content_en = '<p>Strong bones are built over a lifetime — and protecting them requires active effort at every age. Osteoporosis (low bone density) affects millions of people worldwide and dramatically increases the risk of fractures. The good news: bone loss is largely preventable with the right habits.</p><h3>The Science of Bone Health</h3><p>Bone is living tissue that is constantly being broken down and rebuilt. Until about age 30, you build bone faster than you lose it. After 30, the process gradually reverses — making the bone-building years critical. Several factors influence this balance:</p><ul><li><strong>Calcium:</strong> The primary mineral in bone. Adults need 1,000–1,200 mg per day from food (dairy, leafy greens, fortified foods) or supplements if needed.</li><li><strong>Vitamin D:</strong> Essential for calcium absorption. Many people in northern latitudes or who spend little time outdoors are deficient. A blood test can check your level.</li><li><strong>Protein:</strong> The bone matrix is made largely of collagen — a protein. Adequate protein intake supports both bone formation and muscle mass, which protects bones from fracture.</li><li><strong>Weight-bearing exercise:</strong> Walking, jogging, dancing, and resistance training stimulate bone formation. Swimming and cycling, while excellent for cardiovascular fitness, do not provide the mechanical load bones need to grow stronger.</li><li><strong>Avoiding bone-depleting factors:</strong> Smoking, excessive alcohol, high sodium diets, and prolonged use of certain medications (corticosteroids, proton pump inhibitors) can all reduce bone density.</li></ul><h3>Bone Density Testing</h3><p>A DEXA (dual-energy X-ray absorptiometry) scan measures bone mineral density and can predict fracture risk. It is recommended for women over 65, men over 70, and younger individuals with risk factors. Nuclear medicine bone scintigraphy can detect stress fractures, metastatic bone disease, and infections earlier than plain X-rays.</p><p>Do not wait for a fracture to think about your bones. Speak with our team at Caspian Nuclear Medicine Center about bone health screening.</p>'
WHERE id = 10;

UPDATE articles SET
  title_en = 'Symptoms You Should Never Ignore',
  excerpt_en = 'Some symptoms that seem minor can be early warning signs of serious disease. A nuclear medicine specialist shares the warning signs that warrant prompt medical evaluation.',
  content_en = '<p>The human body is remarkably good at signaling when something is wrong — but we are not always good at listening. Some symptoms that are easy to dismiss or attribute to stress and aging can be early indicators of conditions that are far easier to treat when caught early. Here are the warning signs that should always prompt a visit to your doctor.</p><h3>Unexplained Weight Loss</h3><p>Losing more than 5% of your body weight over 6–12 months without trying — and without changes in diet or exercise — can indicate thyroid disease, diabetes, inflammatory bowel disease, or cancer. It should always be investigated.</p><h3>Persistent Bone or Joint Pain</h3><p>Pain that does not resolve with rest and has no clear traumatic cause may reflect stress fractures, bone metastases, arthritis, or infection. A bone scan (nuclear scintigraphy) can detect abnormalities months before plain X-rays show any change.</p><h3>Unusual Fatigue</h3><p>Fatigue is one of the most common complaints — and one of the most commonly ignored. Persistent, unexplained fatigue can signal anemia, hypothyroidism, heart failure, cancer, or depression. It deserves investigation, not acceptance.</p><h3>Palpitations or Chest Discomfort</h3><p>Even brief episodes of irregular heartbeat, chest pressure, or shortness of breath during ordinary activities should be evaluated. A myocardial perfusion scan can reveal reduced blood flow to the heart that predates a heart attack.</p><h3>A New Lump or Nodule</h3><p>Any new lump in the neck, armpit, groin, or thyroid area should be assessed. Most are benign — but the small percentage that are not are far more treatable when caught early.</p><h3>Changes in Urination or Bowel Habits</h3><p>Blood in the urine, increased urinary frequency, or persistent changes in bowel habits lasting more than a few weeks warrant medical evaluation to rule out kidney, bladder, prostate, or colorectal disease.</p><p>If you are experiencing any of these symptoms, do not delay. Early evaluation — including nuclear medicine imaging when indicated — can make an enormous difference in outcomes.</p>'
WHERE id = 11;

UPDATE articles SET
  title_en = 'Healthy Kidneys: What You Can Do',
  excerpt_en = 'The kidneys filter your entire blood supply dozens of times a day. Learn how to protect them — and how nuclear medicine assesses kidney function more accurately than blood tests alone.',
  content_en = '<p>Your kidneys perform one of the most essential functions in the body: filtering waste, balancing fluids, regulating blood pressure, and producing hormones that control red blood cell production. Yet kidney disease is often silent — progressing for years before symptoms appear. Protecting kidney health and detecting problems early are both achievable goals.</p><h3>Key Habits for Kidney Health</h3><ul><li><strong>Stay hydrated.</strong> Drinking adequate water (typically 1.5–2 liters per day for most adults) helps the kidneys flush waste efficiently. Note: if you already have kidney disease, your nephrologist may recommend a different fluid target.</li><li><strong>Manage blood pressure and blood sugar.</strong> Hypertension and diabetes are the two leading causes of chronic kidney disease. Keeping both under control dramatically slows or prevents kidney damage.</li><li><strong>Avoid nephrotoxic medications.</strong> NSAIDs (ibuprofen, naproxen) taken regularly, certain antibiotics, and contrast dyes used in CT scans can damage the kidneys — especially in people already at risk. Always disclose your kidney health status before any imaging or new medication.</li><li><strong>Do not smoke.</strong> Smoking reduces blood flow to the kidneys and accelerates the progression of kidney disease.</li><li><strong>Maintain a healthy diet.</strong> Reducing salt, limiting processed meat, and eating a balanced diet protects both the kidneys and cardiovascular system.</li></ul><h3>How Nuclear Medicine Evaluates Kidney Function</h3><p>Blood creatinine and eGFR tests give a global estimate of kidney function — but they cannot distinguish between the two kidneys or detect subtle regional defects. Nuclear medicine renal scintigraphy (kidney scan) provides far more detail:</p><ul><li>Measures the individual function of each kidney separately — critical before nephrectomy or transplant</li><li>Assesses urinary drainage and detects obstruction</li><li>Evaluates renovascular hypertension (kidney-related high blood pressure)</li><li>Monitors kidney transplant function and detects early rejection</li></ul><p>If you have risk factors for kidney disease — or if you have been told your kidney function is declining — contact Caspian Nuclear Medicine Center. A renal scan can provide information that blood tests simply cannot.</p>'
WHERE id = 12;

UPDATE articles SET
  title_en = 'Are Nuclear Scans Safe for Children?',
  excerpt_en = 'Parents naturally worry when nuclear medicine imaging is recommended for their child. Here we address those concerns honestly — including how pediatric doses are calculated and what safeguards are in place.',
  content_en = '<p>When a doctor recommends a nuclear medicine scan for a child, it is completely natural for parents to feel anxious. The words "radioactive" and "radiation" raise immediate concern. Let us address those concerns with straightforward, evidence-based information.</p><h3>The Short Answer: Yes, With Appropriate Dose Adjustments</h3><p>Nuclear medicine studies are performed in children of all ages — including newborns — when clinically necessary. The key difference from adult scanning is that the radiotracer dose is <strong>carefully scaled to the child body weight</strong>. Pediatric nuclear medicine follows the ALARA principle: As Low As Reasonably Achievable. The dose is the minimum needed to produce a diagnostic image — no more.</p><h3>How Pediatric Doses Are Calculated</h3><p>The North American consensus guidelines (SNMMI/EANM) provide weight-based dose tables for all common pediatric nuclear medicine procedures. A 10 kg child receives a fraction of the adult dose — not a full adult dose. Medical physicists at our center review each case to ensure the dose is appropriate for the child age and weight.</p><h3>Why the Benefit Usually Outweighs the Risk</h3><p>Children are generally referred for nuclear medicine scans when the clinical question cannot be answered by ultrasound or MRI. Common pediatric indications include:</p><ul><li>Vesicoureteral reflux (VUR) — using DMSA renal cortical scintigraphy, which delivers a very low dose</li><li>Bone infections (osteomyelitis) or bone tumors</li><li>Thyroid disorders</li><li>Congenital heart defects</li><li>Brain disorders including epilepsy</li></ul><p>In each of these cases, the diagnostic information obtained from the nuclear medicine scan directly guides treatment decisions that can prevent serious long-term harm. The small radiation exposure is far outweighed by the benefit of an accurate diagnosis.</p><h3>Preparing Your Child</h3><p>Our team at Caspian Nuclear Medicine Center is experienced in working with children. We explain procedures in age-appropriate language, use distraction techniques, and — when necessary — coordinate with pediatric anesthesiology for sedation to ensure the child is comfortable and the image quality is optimal. Parents are welcome to stay with their child throughout the procedure.</p><p>If you have questions about a recommended scan for your child, our nuclear medicine physicians are happy to discuss the specific indication, dose, and benefits in detail before you make a decision.</p>'
WHERE id = 13;
